version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: main
    ports:
      - "5455:5432"

  app:
    build: .
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
      DATABASE_NAME: main
      JWT_KEY: $JWT_KEY
    depends_on:
      - database
    ports:
      - "4000:4000"